name: GitHub Issue Opened Example
on:
  issues:
    types: [opened]
jobs:
  issue_opened:
    # This job always runs when an issue is opened
    name: Issue Opened
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GitHub issue #${{ github.event.issue.number }} has been opened!"
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['new-issue']
            })
