name: GitHub Java Build Example
on:
  push
jobs:
  publish:
    # This job always runs when a Push was made to anything but a tag
    name: Push created
    if: startsWith(github.ref, 'refs/tags/v') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build application
        run: cd workflow-example && mvn --batch-mode --update-snapshots verify
      - name: Deploy artifact
        run: cd workflow-example && mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
