name: GitHub Java Build Example
on:
  push
jobs:
  publish:
    # This job always runs when a Push was made to main branch
    name: Push created
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build application
        run: cd workflow-example && mvn --batch-mode --update-snapshots verify
      - name: Deploy artifact
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir staging && cp workflow-example/target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
