name: GitHub Push Example
on:
  push:
    branches:
      - main
jobs:
  push_on_main:
    # This job always runs when a Push was made to "main" branch
    name: Push to Main created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: examplescript
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Show return value of examplescript
        run: echo "${{steps.examplescript.outputs.result}}"
