name: GitHub Release created Example
on:
  release:
    types: [created]
jobs:
  release_created:
    # This job always runs when a release has been created
    name: Release created
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "A release has been created!"
